### ISSUE TITLE
[FEAT] Add proot support like webtop version

### ISSUE THREAD

**Issue by c4software** [linuxserver/docker-baseimage-rdesktop#66]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add proot command to this base image

### Reason for change

Merge similar image (docker-baseimage-kasmvnc and docker-baseimage-rdesktop) by adding proot to allow users to add their own programs and persistance

### Proposed code change

Add something like this onto the `Dockerfile` :

```
echo "**** proot-apps ****" && \
  mkdir /proot-apps/ && \
  PAPPS_RELEASE=$(curl -sX GET "https://api.github.com/repos/linuxserver/proot-apps/releases/latest" \
    | awk '/tag_name/{print $4;exit}' FS='[""]') && \
  curl -L https://github.com/linuxserver/proot-apps/releases/download/${PAPPS_RELEASE}/proot-apps-x86_64.tar.gz \
    | tar -xzf - -C /proot-apps/ && \
  echo "${PAPPS_RELEASE}" > /proot-apps/pversion && \
```

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-rdesktop

**Comment by c4software** [comment]
Nice ! Thanks a lot 👍
